manifest:
  version: 0.10
  remotes:
    zmkfw:
      url: https://github.com/zmkfirmware/zmk.git
      fetch: +refs/heads/main:refs/remotes/zmkfw/main
  defaults:
    remote: zmkfw
    revision: main
  projects:
    - name: app
      path: app
      revision: main
